DOUBLE_MULTIPLIER = 2
SQUARE_EXPONENT = 2

DEFAULT_VALIDATE = True
DEFAULT_TRANSFORM = True
DEFAULT_DATE_FORMAT = "%Y-%m-%d"
DEFAULT_BATCH_SIZE = 100

MIN_VALUE = 10
MAX_VALUE = 1000
MAX_DATE_OFFSET_DAYS = 365

MINIMUM_FIELD_COUNT = 3

DEFAULT_LOG_FILE_PATH = "processing.log"
LOG_TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"

CSV_HEADER = "ID,NAME,VALUE,DATE,DOUBLED_VALUE,SQUARED_VALUE"
JSON_INDENT = 2

SAMPLE_DATE_FORMAT = "%Y-%m-%d"

DEFAULT_RECORD_COUNT = 50
DEFAULT_INPUT_FILE = "input.csv"
DEFAULT_OUTPUT_JSON = "output.json"
DEFAULT_OUTPUT_XML = "output.xml"
DEFAULT_OUTPUT_CSV = "output.csv"
DISPLAY_DATE_FORMAT = "%m/%d/%Y"
FILTER_MIN_VALUE = 100
