from __future__ import annotations

STEP_GENERATE = "GENERATE"
STEP_REFINE_TONE = "REFINE_TONE"
STEP_SUMMARIZE = "SUMMARIZE"
STEP_TRANSLATE = "TRANSLATE"
STEP_ENRICH_WITH_CONTEXT = "ENRICH_WITH_CONTEXT"
STEP_POST_PROCESS = "POST_PROCESS"
STEP_NOOP = "NOOP"

COND_ALWAYS = "ALWAYS"
COND_OUTPUT_CONTAINS = "OUTPUT_CONTAINS"
COND_METADATA_EQUALS = "METADATA_EQUALS"

DEFAULT_GENERATE_PREFIX = "Generated: "
DEFAULT_SUMMARY_MAX_LEN = 60
MIN_SUMMARY_MAX_LEN = 10

TRACE_OUTPUT_PREVIEW_MAX_CHARS = 200

MSG_CONDITION_FALSE = "condition evaluated to false"
MSG_EXECUTING_FALLBACK = "executing fallback step"

ERR_SIMULATED_TRANSLATION_FAILURE = "Simulated translation failure"

SUMMARY_PREFIX = "Summary of: "
TRANSLATED_PREFIX_FMT = "Translated[{lang}]: "

TRACE_WORKFLOW_START = "workflow_start"
TRACE_WORKFLOW_END = "workflow_end"
TRACE_STEP_START = "step_start"
TRACE_STEP_END = "step_end"
TRACE_STEP_ERROR = "step_error"
TRACE_STEP_SKIPPED = "step_skipped"
TRACE_STEP_FALLBACK_START = "step_fallback_start"
TRACE_CONDITION_EVALUATED = "condition_evaluated"
ALLOWED_POST_PROCESS_MODES = {"strip", "upper", "lower"}
DEMO_INITIAL_INPUT = "A waterproof hiking backpack with 30L capacity."

